### PR TITLE
add pr template with DCO

### PR DESCRIPTION
**Pull request by bjohansebas**
- Related to https://github.com/openjs-foundation/project-status/issues/15 and https://github.com/expressjs/express/pull/6048

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by UlisesGascon** [comment]
Note: This won't be merged until https://github.com/expressjs/express/pull/6048 is accepted and merged.

**Comment by bjohansebas** [comment]
When this is merged, I’ll make a PR for the other two organizations.

**Comment by bjohansebas** [comment]
ping

**Review by wesleytodd — APPROVED** [review]

**Comment by wesleytodd** [comment]
@bjohansebas, Instead of pining in an issue it would be better to post a link in the slack. I personally have over 400 notifications I am trying to get to and having even more just for comments like this does not help us get to them. This is not a criticism, just a suggestion for the future. 😄

**Pull request merged**
